export const formInitialState = {
    name: null,
    type: null,
    minPrice: null,
    maxPrice: null,
    isUnique: false,
    quantity: 1,
    isPureBreed: true,
    breed: '',
    fatherBreed: '',
    motherBreed: '',
    birthWeight: null,
    birthDate: null,
    farmFrom: null,
    houseType: null,
    adg: null,
    fcr: null,
    bft: null,
    lsba: null,
    leftTeats: null,
    rightTeats: null,
    otherDetails: null,
};